# Generated by Django 3.2.3 on 2021-05-28 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_pokemons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stats',
            options={'verbose_name_plural': 'Stats'},
        ),
    ]
