# Generated by Django 3.2.3 on 2021-05-28 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_pokemons', '0002_alter_stats_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='stats',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='attack',
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='defense',
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='hp',
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='special_attack',
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='special_defense',
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='speed',
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='generation',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.DeleteModel(
            name='Stats',
        ),
    ]
