# Generated by Django 3.2.3 on 2021-05-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_pokemons', '0003_auto_20210528_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='total',
            field=models.PositiveSmallIntegerField(default=50),
        ),
    ]
