# Generated by Django 3.2.3 on 2021-05-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_pokemons', '0004_pokemon_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type2',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
