# Generated by Django 3.2.3 on 2021-05-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_pokemons', '0006_alter_pokemon_type2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='total',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
